# Generated by Django 3.2.16 on 2023-01-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.TimeField(null=True, verbose_name='birthday'),
        ),
    ]
