# Generated by Django 3.2.16 on 2023-01-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibook', '0001_initial'),
        ('account', '0004_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='book_like', to='bibook.Book', verbose_name='like book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='book_save', to='bibook.Book', verbose_name='save book'),
        ),
    ]
