# Generated by Django 4.1.4 on 2023-01-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20230118_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved',
        ),
    ]
