# Generated by Django 4.1.4 on 2023-01-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibook', '0006_book_comment_book'),
        ('account', '0006_remove_user_liked_remove_user_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='book_like', to='bibook.book', verbose_name='like book'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='book_save', to='bibook.book', verbose_name='save book'),
        ),
    ]
