services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core/:/code
    ports:
      - "8000:8000"

  redis:
    image: redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./dbs/redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"

