# Generated by Django 3.2.16 on 2023-01-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('translator', models.CharField(max_length=255, verbose_name='translator')),
                ('about', models.TextField(verbose_name='about')),
                ('length', models.IntegerField(verbose_name='length')),
                ('language', models.CharField(max_length=50, verbose_name='language')),
                ('publisher', models.CharField(max_length=255, verbose_name='publisher')),
                ('format', models.CharField(max_length=8, verbose_name='format')),
                ('file_size', models.CharField(max_length=8, verbose_name='size')),
                ('url', models.URLField(max_length=255, verbose_name='link')),
                ('view', models.IntegerField(verbose_name='view')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='update_time')),
                ('like', models.IntegerField(verbose_name='like')),
                ('save', models.IntegerField(verbose_name='save')),
                ('download', models.IntegerField(verbose_name='download')),
                ('category', models.ManyToManyField(to='bibook.category', verbose_name='category')),
            ],
        ),
    ]
