# Generated by Django 3.2.16 on 2023-01-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='download',
            field=models.IntegerField(default=0, verbose_name='download'),
        ),
        migrations.AlterField(
            model_name='book',
            name='like',
            field=models.IntegerField(default=0, verbose_name='like'),
        ),
        migrations.AlterField(
            model_name='book',
            name='save',
            field=models.IntegerField(default=0, verbose_name='save'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='translator'),
        ),
        migrations.AlterField(
            model_name='book',
            name='view',
            field=models.IntegerField(default=0, verbose_name='view'),
        ),
    ]
