# Generated by Django 3.2.16 on 2023-01-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibook', '0002_auto_20230118_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='bibook.Category', verbose_name='category'),
        ),
    ]
