# Generated by Django 4.1.4 on 2023-01-21 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibook', '0005_remove_comment_book_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('translator', models.CharField(blank=True, max_length=255, null=True, verbose_name='translator')),
                ('about', models.TextField(verbose_name='about')),
                ('length', models.IntegerField(verbose_name='length')),
                ('language', models.CharField(max_length=50, verbose_name='language')),
                ('publisher', models.CharField(max_length=255, verbose_name='publisher')),
                ('format', models.CharField(max_length=8, verbose_name='format')),
                ('file_size', models.CharField(max_length=8, verbose_name='size')),
                ('url', models.URLField(max_length=255, verbose_name='link')),
                ('view', models.IntegerField(default=0, verbose_name='view')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='update_time')),
                ('like', models.IntegerField(default=0, verbose_name='like')),
                ('save', models.IntegerField(default=0, verbose_name='save')),
                ('download', models.IntegerField(default=0, verbose_name='download')),
                ('category', models.ManyToManyField(to='bibook.category', verbose_name='category')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bibook.book', verbose_name='book'),
            preserve_default=False,
        ),
    ]
