# Generated by Django 4.1.4 on 2023-01-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibook', '0006_book_comment_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
    ]
