# Generated by Django 4.1.4 on 2023-01-21 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibook', '0007_alter_book_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='like',
            new_name='liked',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='save',
            new_name='saved',
        ),
    ]
