# Generated by Django 3.2.16 on 2023-01-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibook', '0008_rename_like_book_liked_rename_save_book_saved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='bibook.Category', verbose_name='category'),
        ),
    ]
