# Generated by Django 4.1.4 on 2023-01-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibook', '0009_auto_20230123_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='delete'),
        ),
    ]
